language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

before_install:
  - nvm install stable
  - npm install netlify-cli -g
  - export COMMIT_MSG=$(git log -1 --format='%h %<(50,trunc)%s')
  - export DEPLOY_MSG=${COMMIT_MSG//[\'\"]/}

env:
  - NETLIFY_SITE_ID=4e9fea2e-d99c-484e-be1a-9d8605393f4e
  # NETLIFY_AUTH_TOKEN set in travis settings

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: netlify deploy --dir _book --message "$DEPLOY_MSG"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
